#!/bin/sh

### BEGIN INIT INFO
# Provides:          eth0_init
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Activates eth0 interface
# Description:       Activates the eth0 network interface
#
### END INIT INFO

# Author: BVC

sudo -u pi bash /home/pi/eth0_init.sh &
