#!/bin/sh

### BEGIN INIT INFO
# Provides:          kivy_init
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kivy startup
# Description:       Starts kivy app
#
### END INIT INFO

# Author: BVC

sudo -u pi /usr/local/bin/fbcp & 
sudo -u pi /usr/bin/python /home/pi/kivy-test/main.py &

