#!/bin/sh

### BEGIN INIT INFO
# Provides:          wifi_ap_mode
# Required-Start:    $local_fs networking
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: BEEweb daemon
# Description:       Starts wifi AP mode script
#
### END INIT INFO

# Author: BVC

if [ ! -f /etc/wpa_supplicant/wpa_supplicant.conf ]; then
	echo "Switching WiFi to AP mode..."
	/bin/bash /home/pi/wifi_ap_mode.sh
else
    echo "Client mode..."
    /bin/bash /home/pi/wifi_client_mode.sh
fi

