#!/usr/bin/env bash
if [ -z "$1" ];then
    pushd workspace
else
    pushd workspace-$1
fi

FILENAME=$(basename `ls . |  grep .img | tail -n 1` .img)  
BEEWEBPI_FILENAME=$(echo $FILENAME-`cat ../filesystem/root/etc/beewebpi_version` | sed 's/raspbian/beewebpi/')
mv ${FILENAME}.img $BEEWEBPI_FILENAME.img
zip $BEEWEBPI_FILENAME.zip $BEEWEBPI_FILENAME.img

popd
